---
abstract: 'Generates XML and communicates with AutoDNS'
author:
  - 'Juerd Waalboer <juerd@tnx.nl>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS-AutoDNS
requires:
  Carp: 0
  Exporter: 0
  File::Basename: 0
  File::Temp: 0
  IO::File: 0
  IO::Handle: 0
  LWP::Simple: 0
  Net::DNS: 0
  Net::DNS::RR: 0
  XML::LibXML: 0
  constant: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nupfel/Net-DNS-AutoDNS/issues
  homepage: https://github.com/nupfel/Net-DNS-AutoDNS/wiki
  repository: git://github.com/nupfel/Net-DNS-AutoDNS.git
version: 0.1
